# -*- coding: utf-8 -*-

db.define_table('configfile',
        Field('configfile', 'upload'))

db.define_table('baselayers',
        Field('baselayer', 'string', length=32, requires=IS_NOT_EMPTY(), label='baseLayer',
              caption='číselník baseLayer pro tabulku places'),
        )

db.define_table('datatypes',
        Field('dtid', 'string', length=32, requires=IS_NOT_EMPTY(), label='id',
              caption='označení'),
        Field('dtcs', 'string', length=128, requires=IS_NOT_EMPTY(), label='cs',
              caption='český popis'),
        Field('dten', 'string', length=128, label='en',
              caption='anglický popis / english description'),
        )

db.define_table('ekosystemtypes',
        Field('etid', 'string', length=32, requires=IS_NOT_EMPTY(), label='id',
              caption='označení'),
        Field('etcs', 'string', length=128, requires=IS_NOT_EMPTY(), label='cs',
              caption='český popis'),
        Field('eten', 'string', length=128, label='en',
              caption='anglický popis / english description'),
        )

db.define_table('places',
        Field('ptitlecs', 'string', length=255, requires=IS_NOT_EMPTY(), label='title',
              caption='označení místa (bez uvozovek)'),
        Field('ptitleen', 'string', length=255, label='title en',
              caption='označení místa anglicky / english (nepovinné)'),
        Field('baselayer_id', db.baselayers, requires=IS_IN_DB(db.baselayers), label='baseLayer',
              caption='nabízené baseLayer lze editovat v samostatné tabulce'),
        Field('pextentl', 'decimal(6,3)', requires=IS_NOT_EMPTY(), label='extent L',
              caption='souřadnice, Left, příklad: 15.152'),
        Field('pextentb', 'decimal(6,3)', requires=IS_NOT_EMPTY(), label='extent B',
              caption='souřadnice, Bottom, příklad: 49.429'),
        Field('pextentr', 'decimal(6,3)', requires=IS_NOT_EMPTY(), label='extent R',
              caption='souřadnice, Right, příklad: 15.355'),
        Field('pextentt', 'decimal(6,3)', requires=IS_NOT_EMPTY(), label='extent T',
              caption='souřadnice, Top, příklad: 49.524'),
        )

db.define_table('campaigns',
        Field('places_id', db.places, requires=IS_NOT_EMPTY(), label='places',
              caption='místo'),
        Field('cdaterange', 'date', requires=IS_NOT_EMPTY(), label='datum (od)',
              caption='jediné nebo počáteční datum pro dateRange'),
        Field('cdaterange2', 'date', label='datum do',
              caption='konečné datum pro dateRange (pokud se liší od počátečního)'),
        )

db.define_table('datasets',
        Field('dtitlecs', 'string', length=255, requires=IS_NOT_EMPTY(), label='title',
              caption='označení místa (bez uvozovek)'),
        Field('dtitleen', 'string', length=255, label='title en',
              caption='označení místa anglicky / english (nepovinné)'),
        Field('ddate', 'datetime', requires=IS_NOT_EMPTY(), label='date',
              caption='datum a čas, doporučeno v UTC (tz = Z)'),
        Field('ddatetz', 'string', length=1, default='Z', requires=IS_NOT_EMPTY(), label='date tz',
              caption='časová zóna pro date'),
        #Field('datatypes_id', db.datatypes, requires=IS_NOT_EMPTY(), label='datatypes',
        #      caption=''),
        #Field('ekosystemtypes_id', db.ekosystemtypes, requires=IS_NOT_EMPTY(), label='ekosystemtypes',
        #      caption=''),
        Field('dlayer', 'string', length=128, requires=IS_NOT_EMPTY(), label='layer/sublayer',
              caption='sublayer pro layer, příklad: kopaniny_dehtare_AISA_29062010'),
        Field('dspatialresolution', 'decimal(5,2)', label='spatialResolution',
              caption='spatialResolution v [m], např. 2.5 (nepovinné)'),
        Field('dpointspermeter', 'decimal(5,1)', label='pointsPerMeter',
              caption='bodů na [m], např. 10 (nepovinné)'),
        Field('dspectralrangefrom', 'decimal(5,1)', label='spectralRange from',
              caption='spektrální rozsah od.. [nm] (nepovinné)'),
        Field('dspectralrangeto', 'decimal(5,1)', label='spectralRange to',
              caption='spektrální rozsah od.. [nm] (nepovinné)'),
        Field('dspectralresolutionfrom', 'decimal(6,3)', label='spectralResolution (from)',
              caption='jediná (nebo počáteční) spektrální přesnost [nm] (nepovinné)'),
        Field('dspectralresolutionto', 'decimal(6,3)', label='spectralResolution to',
              caption='spektrální přesnost [nm], druhá hodnota, je-li uvedena (nepovinné)'),
        Field('dnumberofbands', 'integer', label='numberOfBands',
              caption='počet pásem (nepovinné)'),
        Field('ddescriptioncs', 'string', length=255, requires=IS_NOT_EMPTY(), label='description',
              caption='popis (bez uvozovek, nepovinné)'),
        Field('ddescriptionen', 'string', length=255, label='description en',
              caption='popis anglicky / description in english (nepovinné)'),
        )
